---

- name: install docker 
  shell: curl -fsSL https://get.docker.com | sh
 

- name: Join the pending Swarm worker nodes.
  shell: docker swarm join --token {{ hostvars['managetoken']['my_server_fact'] }} {{ hostvars['localhost']['masterip'] }}:{{ docker_swarm_port }}
        
     #   docker swarm join \
    #--token SWMTKN-1-49nj1cmql0jkz5s954yi3oex3nedyz0fb0xx14ie39trti4wxv-8vxv8rssmk743ojnwacrr2e7c \   # 192.168.99.100:2377