---
- name: create master instance
  hosts: localhost
  become: sudo
  become_user: root

  roles:
    - instance
    
- name: master_instance
  remote_user: ubuntu
  hosts: master_node
  become: yes
  become_method: sudo
  become_user: root
  
  roles:
    - install_docker
    
- name: node1_docker
  remote_user: ubuntu
  hosts: slave_node
  become: yes
  become_method: sudo
  become_user: root

  vars:
    docker_swarm_port: 2377
  
  roles:
    - slavenode
    
- name: node2_instance
  remote_user: ubuntu
  hosts: slave_node2
  become: yes
  become_method: sudo
  become_user: root

  vars:
    docker_swarm_port: 2377
  
  roles:
    - slavenode2

- name: master_instance
  remote_user: ubuntu
  hosts: master_node
  become: yes
  become_method: sudo
  become_user: root
  
  roles:
    - create_container
    

    
    
    
    
    